version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=test-my-docker
      - MYSQL_USER=yui
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=supperpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: on-failure

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=my-docker
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - ./mongo-db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf